# ThisConfFile: wg_mumstv_10.conf
# Tag: mumstv
# PeerId: 10
# ServerConfFile: wg_mumstv.conf
# PublicKey = bhtR6xLL5uZjgGXjOOcSfofWRtQg/s3Z5BYzfo12xVs=
[Interface]
PrivateKey = QIVU64QjP2kQWodAkai2Y0GH2nOYbStaATy5qQgrQ0c=
Address = fd00::23:10/120, 192.168.23.10/24


[Peer]
PublicKey = 0JekPK59Jnsj7jed9m/0WFPBSG+CWzejyp12s+A1Oio=
AllowedIPs = fd00::23:1/128, 192.168.23.1/32
Endpoint = mumstv.com:18000
PersistentKeepalive = 25
