#!/bin/bash

# The intent is that a customized version of this file will be generated by mumstv.com in
# response to an authenticated request for a new camera

# On mumstv.com
# - wireguard
# - caddy
# - redirect

# This script

# wireguard
# - service
# - config file

# camera
# - config.txt
# - user in video group

# server
# - mjpeg source
# - http server

# redirect
# - key
# - service

# Fail loudly
set -euo pipefail
trap 'rc=$?;set +ex;if [[ $rc -ne 0 ]];then trap - ERR EXIT;echo 1>&2;echo "*** fail *** : code $rc : $DIR/$SCRIPT $ARGS" 1>&2;echo 1>&2;exit $rc;fi' ERR EXIT
ARGS="$*"
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT="$(basename "${BASH_SOURCE[0]}")"

name="mumstv-setup"


logdir="${name}-logs"

mkdir -p "$logdir"

#sudo ls -la

{
    set -x

    ####################
    #
    # wireguard
    #
    export DEBIAN_FRONTEND=noninteractive
    #apt-get update
    #apt-get install -y wireguard wireguard-tools

    tee /etc/default/wireguard <<"EOF"
# Environment settings for wireguard (wg and wg-quick)

WG_COLOR_MODE=never
WG_HIDE_KEYS=always
WG_ENDPOINT_RESOLUTION_RETRIES=

EOF

    # one way to disable wireguard: rename this file, removing the ".NOT"
    touch /etc/wireguard/wireguard_not_to_be_run.NOT

    tee /etc/systemd/system/wireguard@.service <<"EOF"
[Unit]
Description=Wireguard
Documentation=man:wg(8) man:wg-quick(8)
After=nss-lookup.target
ConditionPathExists=!/etc/wireguard/wireguard_not_to_be_run

[Service]
Type=oneshot
RemainAfterExit=yes
EnvironmentFile=-/etc/default/wireguard
ExecStart=/usr/bin/wg-quick up /etc/wireguard/%i.conf
ExecStop=/usr/bin/wg-quick down /etc/wireguard/%i.conf
Restart=on-failure
RestartSec=21

[Install]
WantedBy=multi-user.target
#Alias=wireguard.service

EOF

    # Per peer wireguard: wg_mumstv_11.conf
    wireguard_conf=wg_mumstv_11
    tee /etc/wireguard/${wireguard_conf}.conf <<EOF
# ThisConfFile: ${wireguard_conf}.conf
EOF
    # Per peer details from mumstv.com
    tee -a /etc/wireguard/${wireguard_conf}.conf <<"EOF"
# Tag: mumstv
# PeerId: 11
[Interface]
PrivateKey = IAShOJrqlqZtEma3l5Tu/9PiNqgL+4GbtpcFTSz7FWA=
# PublicKey = voUPV4i/kzzPHvAWrGXToYcZLJjin13z29oa5LckB24=
Address = fd00::23:11/120, 192.168.23.11/24


[Peer]
# ServerConfFile: wg_mumstv.conf
PublicKey = 0JekPK59Jnsj7jed9m/0WFPBSG+CWzejyp12s+A1Oio=
AllowedIPs = fd00::23:1/128, 192.168.23.1/32
Endpoint = mumstv.com:18000
PersistentKeepalive = 25

EOF
    chmod go-rwx /etc/wireguard/${wireguard_conf}.conf

    systemctl daemon-reload
    systemctl disable wireguard@${wireguard_conf}.service || true
    systemctl enable wireguard@${wireguard_conf}.service
    systemctl start wireguard@${wireguard_conf}.service
    ping -c 3 -4 192.168.23.1
    ping -c 3 -6 fd00::23:1
    wg
    ip route show table all

    #
    # wireguard
    #
    ####################


    ####################
    #
    # camera
    #

    #
    # camera
    #
    ####################


    ####################
    #
    # server
    #

    #
    # server
    #
    ####################


    ####################
    #
    # redirect
    #

    #
    # redirect
    #
    ####################



    echo
    echo OK

} 2>&1 | tee "${logdir}"/${name}_$(date '+%Y-%m-%d-%H%M-%S').log
