#!/bin/bash

# The intent is that a customized version of this file will be generated by mumstv.com in
# response to an authenticated request for a new camera

# On mumstv.com
# - wireguard
# - caddy
# - redirect

# This script

# wireguard
# - service
# - config file

# camera
# - config.txt
# - user in video group

# server
# - mjpeg source
# - http server

# redirect
# - key
# - service

# Fail loudly
set -euo pipefail
trap 'rc=$?;set +ex;if [[ $rc -ne 0 ]];then trap - ERR EXIT;echo 1>&2;echo "*** fail *** : code $rc : $DIR/$SCRIPT $ARGS" 1>&2;echo 1>&2;exit $rc;fi' ERR EXIT
ARGS="$*"
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT="$(basename "${BASH_SOURCE[0]}")"

name="mumstv-setup"


logdir="${name}-logs"

mkdir -p "$logdir"

#sudo ls -la

{
    set -x

    ####################
    #
    # wireguard
    # - assumes installed packages: wireguard wireguard-tools

    tee /etc/default/wireguard <<"EOF"
# Environment settings for wireguard (wg and wg-quick)

WG_COLOR_MODE=never
WG_HIDE_KEYS=always
WG_ENDPOINT_RESOLUTION_RETRIES=

EOF

    # one way to disable wireguard: rename this file, removing the ".NOT"
    touch /etc/wireguard/wireguard_not_to_be_run.NOT

    tee /etc/systemd/system/wireguard@.service <<"EOF"
[Unit]
Description=Wireguard
Documentation=man:wg(8) man:wg-quick(8)
After=nss-lookup.target
ConditionPathExists=!/etc/wireguard/wireguard_not_to_be_run

[Service]
Type=oneshot
RemainAfterExit=yes
EnvironmentFile=-/etc/default/wireguard
ExecStart=/usr/bin/wg-quick up /etc/wireguard/%i.conf
ExecStop=/usr/bin/wg-quick down /etc/wireguard/%i.conf
Restart=on-failure
RestartSec=21

[Install]
WantedBy=multi-user.target
#Alias=wireguard.service

EOF

    # Per peer wireguard configuration
    this_conf=wg_mumstv_11
    Tag=mumstv
    PeerId=11
    ThisPrivateKey='IAShOJrqlqZtEma3l5Tu/9PiNqgL+4GbtpcFTSz7FWA='
    ThisPublicKey='voUPV4i/kzzPHvAWrGXToYcZLJjin13z29oa5LckB24='
    ThisAddress='fd00::23:11/120, 192.168.23.11/24'
    PeerConfFile='wg_mumstv.conf'
    PeerPublicKey='0JekPK59Jnsj7jed9m/0WFPBSG+CWzejyp12s+A1Oio='
    PeerAllowedIPs='fd00::23:1/128, 192.168.23.1/32'
    PeerEndpoint='mumstv.com:18000'

    tee /etc/wireguard/${this_conf}.conf <<EOF
# ThisConfFile: ${this_conf}.conf
# Tag: $Tag
# PeerId: $PeerId
[Interface]
PrivateKey = $ThisPrivateKey
# PublicKey = $ThisPublicKey
Address = $ThisAddress

[Peer]
# PeerConfFile: $PeerConfFile
PublicKey = $PeerPublicKey
AllowedIPs = $PeerAllowedIPs
Endpoint = $PeerEndpoint
PersistentKeepalive = 25

EOF
    chmod go-rwx /etc/wireguard/${this_conf}.conf

    systemctl daemon-reload
    systemctl disable wireguard@${this_conf}.service || true
    systemctl enable wireguard@${this_conf}.service
    systemctl start wireguard@${this_conf}.service
    ping -c 3 -4 192.168.23.1
    ping -c 3 -6 fd00::23:1
    wg
    ip route show table all

    #
    # wireguard
    #
    ####################


    ####################
    #
    # camera
    #

    camera_overlay=imx219,rotation=180
    sed -i  -e 's/^camera_auto_detect=1/# camera_auto_detect=1  # mumstv/' /boot/firmware/config.txt
    grep -e '^camera_auto_detect=0' /boot/firmware/config.txt || printf '\n# mumstv\n[all]\ncamera_auto_detect=0\ndtoverlay=%s\n\n' "$camera_overlay" | tee -a /boot/firmware/config.txt

    #
    # camera
    #
    ####################


    ####################
    #
    # server
    #

    #
    # server
    #
    ####################


    ####################
    #
    # redirect
    #

    #
    # redirect
    #
    ####################



    set +x
    echo
    echo OK

} 2>&1 | tee "${logdir}"/${name}_$(date '+%Y-%m-%d-%H%M-%S').log
